[phases.setup]
nixPkgs = ["...", "mariadb-connector-c"]
nixLibs = ["...", "mariadb-connector-c.dev"]

[phases.install]
cmds = [
  "pip install -r requirements.txt"
]

[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT app:app"